import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Link from 'next/link'
import Repo from '../components/Repo'


function Home( {data} ) {
  
const [filter, setFilter] = useState({ratings:["1","2","3","4","5"]});


function handleFilter (e) {
  if (e.target.value === "5"){
    console.log("5");
  }
}





//testing if the data can be sorted - created an array using the same format
const sortedData = ["2017-06-25T20:50:11Z","2018-06-25T20:50:11Z", "2019-06-25T20:50:11Z", "2020-06-25T20:50:11Z"];
//sorted the data with a simple function for comparing
sortedData.sort(function(a,b){return a - b})
console.log(sortedData);

data.items.sort(function(a,b){return a - b})
console.log(data.items);

const newDate =[];

function addTime () {
  newDate.push(data.items)
  
  newDate.sort(function(a,b){return a.created_at - b.created_at})
  .map((d)=> (
    console.log(d.name)
  ))

}
 
addTime()

  return (
    <div>
      <Head>
        <title>Best Github repo's </title>
        <meta name="description" content="Generated by shar" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl text-center text-black mb-10 ">Gitub Repo</h1>
      <label>5</label>
      <input type="checkbox" value={5} onClick={handleFilter}  />
      <div className="grid grid-cols-3 grid-rows-2 gap-2 bg-black text-white">
         {data.items.sort(function(a,b) {return a.created_at - b.created_at})
         .map((d)=> (
           <div key={d.id} className=" border-red-600 p-5">
           <h1 className="text-2xl font-bold">{d.name}</h1>
           <p className="mb-5">{d.description}</p>
         
           <p>{d.created_at}</p>
            <Link href={d.html_url}>
            <a className="bg-white text-black font-bold rounded-lg">Click me</a>
            </Link>
        </div>
         ))}
 

           
          
         
  </div>
     
    
      </div>
    
  );
}

export async function getServerSideProps() {
  const res= await fetch('https://api.github.com/search/repositories?q=created:%3E2017-01-10&sort=stars&order=desc')
  const data = await res.json()



  return {
    props: {
      data
    }, 
  }
}

export default Home;
